name: Daily EcoWitt List

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily
  workflow_dispatch:

jobs:
  pull-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r collector/ecowitt/requirements_ecowitt_list.txt
      - name: Retrieve the secret and run Python script
        env:
          BOCHUM_ECOWITT_APPLICATION_KEY: ${{ secrets.BOCHUM_ECOWITT_APPLICATION_KEY }}
          BOCHUM_ECOWITT_API_KEY: ${{ secrets.BOCHUM_ECOWITT_API_KEY }}
        run: python collector/ecowitt/collect_ecowitt_list.py
      - name: Commit and push CSV file
        run: |
          git config --global user.email "philipp.zuber@posteo.de"
          git config --global user.name "zuberspace"
          git add --all data/ENVI/ecowitt_gw2001/
          git commit -m "Daily weather update (EcoWitt GW2001)"
          git push
