name: ENVI EcoWitt CKAN Daily

on:
  schedule:
    - cron: '15 3 * * *' # Runs daily
  workflow_dispatch:

jobs:
  pull-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/ecowitt/requirements_ecowitt_weather.txt

      - name: Upload data to CKAN
        env:
          RVR_BOCHUM_CKAN: ${{ secrets.RVR_BOCHUM_CKAN }}
        run: python tools/ecowitt/ecowitt_ckan_upload.py
