name: ENVI EcoWitt Weather Daily

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily
  workflow_dispatch:

jobs:
  pull-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/ecowitt/requirements_ecowitt_weather.txt

      - name: Retrieve the secret and run EcoWitt Python script
        env:
          BOCHUM_ECOWITT_APPLICATION_KEY: ${{ secrets.BOCHUM_ECOWITT_APPLICATION_KEY }}
          BOCHUM_ECOWITT_API_KEY: ${{ secrets.BOCHUM_ECOWITT_API_KEY }}
        run: python tools/ecowitt/ecowitt_collect_weather.py

      - name: Aggregate EcoWitt data
        run: python tools/ecowitt/ecowitt_aggregate_weather.py

      - name: Commit and push CSV file
        run: |
          git config --global user.email "philipp.zuber@posteo.de"
          git config --global user.name "zuberspace"
          git add --all data/ENVI/ecowitt_gw2001/
          git commit -m "Daily weather update (EcoWitt GW2001)"
          git push
