name: TRAN Vehicle Inventory from SharePoint

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  repository_dispatch:
    types: [StBo_OpenData_VehicleInventory]#

jobs:
  run-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

  #ToDo
